#ifndef MASTER_PINS_H
#define MASTER_PINS_H

#define CE_PIN 9
#define CSN_PIN 10

#define SETUP_BUTTON_PIN 4
#define START_BUTTON_PIN 6
#define SETUP_LED_PIN 5
#define START_LED_PIN 7

#define POTENTIOMETER_MODE_PIN A0
#define POTENTIOMETER_DIFFICULTY_PIN A1

#endif