#ifndef MASTER_PINS_H
#define MASTER_PINS_H

#define CE_PIN 9
#define CSN_PIN 10

#define SETUP_BUTTON_PIN 5
#define START_BUTTON_PIN 7
#define SETUP_LED_PIN 4
#define START_LED_PIN 6

#define POTENTIOMETER_MODE_PIN A0
#define POTENTIOMETER_NORMAL_SPEED_PIN A1
#define POTENTIOMETER_DIFFICULTY_PIN A1

#define MP3_RX_PIN 3
#define MP3_TX_PIN 2

#endif